name: rickmyers
favicon: null
layout_spectrum: 0.49629257153719664
typography_spectrum: 0.21198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000800'
    - '#2b302f'
    - '#f4f2f3'
    - '#4c800d'
    - '#b8ca48'
  brandStrength: 0.4375
  lightness: 0.6182164237834513
  saturation: 0.4593687078449875
  rhythmicContrast: 0.5362550027202815
purpose: []
